services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: operational_monitoring
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s


  station-loader:
    build:
      context: ./station-loader
      dockerfile: Dockerfile
    container_name: station-loader
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: operational_monitoring
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_PORT: 3306
      DATA_FILE_PATH: /app/data/stations.csv

    volumes:
      - ./data:/app/data:ro

    depends_on:
      mysql:
        condition: service_healthy


  broker:
    image: apache/kafka:4.3.1
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      
      KAFKA_LISTENERS: "CONTROLLER://:29093,INTERNAL://:19092,EXTERNAL://:9092"

      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://broker:19092,EXTERNAL://localhost:9092"

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    
    healthcheck:
      test: 
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s


  producer:
    build: 
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    environment:
      DATA_FILE_PATH: /app/data/activity_readings.csv
      KAFKA_BOOTSTRAP_SERVERS: "broker:19092"
      KAFKA_TOPIC_NAME: activity-readings
      KAFKA_CLIENT_ID: "readings.producer"
      PUBLISH_DELAY_SECONDS: "0.1"

    volumes:
      - ./data:/app/data:ro

    depends_on:
      broker:
        condition: service_healthy
      station-loader:
        condition: service_completed_successfully


  mongo:
    image: mongo:8.0.4
    container_name: mongo
    ports:
      - "27017:27017"
    
    volumes:
      - mongo-data:/data/db

    healthcheck:
      test: 
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--eval",
          "db.adminCommand('ping')"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


  raw-consumer:
    build:
      context: ./raw-consumer
      dockerfile: Dockerfile
    container_name: raw-consumer
    environment:
      KAFKA__BOOTSTRAP_SERVERS: "broker:19092"
      KAFKA__GROUP_ID: "raw-consumer"
      KAFKA_CLIENT_ID: "operational-monitoring-group"
      KAFKA_TOPIC: "activity-readings"

      MONGO__URI: "mongodb://mongo:27017"
      MONGO__DATABASE: "operational-monitoring"
      MONGO__COLLECTION: "raw_readings"

    depends_on:
      broker:
        condition: service_healthy
      mongo:
        condition: service_healthy


volumes:
  mysql-data:
  mongo-data: