

CREATE TABLE IF NOT EXISTS Stations (
	Id VARCHAR(50) PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	Sector VARCHAR(100) NOT NULL,
	Status VARCHAR(20) NOT NULL,
	CreatedAt DATETIME NOT NULL
);



CREATE TABLE IF NOT EXISTS Anomalies (
	Id BIGINT PRIMARY KEY AUTO_INCREMENT,
	EventId VARCHAR(100) NOT NULL  UNIQUE,
	SourceId VARCHAR(50) NOT NULL,
	Value DOUBLE NOT NULL,
	Mean DOUBLE NOT NULL,
	StandardDeviation DOUBLE NOT NULL,
	ZScore DOUBLE NULL,
	Severity VARCHAR (20) NOT NULL,
	Status VARCHAR(20) NOT NULL DEFAULT 'New',
	DetectedAt DATETIME NOT NULL,
	CONSTRAINT fk_sourceId
	FOREIGN KEY (SourceId)
	REFERENCES Stations(Id)
);


CREATE TABLE IF NOT EXISTS AlertLogs (
	Id BIGINT PRIMARY KEY AUTO_INCREMENT,
	AnomalyId BIGINT NOT NULL,
	SentAt DATETIME NOT NULL,
	Attempts INT NOT NULL,
	CONSTRAINT fk_AnomalyId
	FOREIGN KEY (AnomalyId)
	REFERENCES Anomalies(Id)
);